### ISSUE TITLE
Stuck on "Loading new item into cache from data list starting with"

### ISSUE THREAD

**Issue by bywbilly** [f90/AdversarialAudioSeparation#4]
Hi, 

Thanks for your excellent code. I am trying to reproduce your results, however, the training will stuck on loading some item into cache. Below is the running output log:

![image](https://user-images.githubusercontent.com/10766902/51260840-25f60f80-197d-11e9-88a0-26bdf0034bdb.png)

Do you have any idea about that? The program stuck on this line: `self.update_next_cache_item(self.communication_queue.get())`

**Comment by bywbilly** [comment]
Ping @f90

**Comment by f90** [comment]
Hey,
this issue was present in my other project as well ([see here](https://github.com/f90/Wave-U-Net/issues/1)) and I managed to fix it by using the scipy resample method instead of the one from librosa (don't ask me why!). I committed a fix to the repository. Please update your code, run again and see if it's fixed now.

**Comment by f90** [comment]
If this still occurs, I think it should at least be fixed if you do not do any resampling during training at all, since in my efforts to fix this, I always had freeze issues like this with the resampling function. So maybe you can preprocess the data yourself first to convert it to the desired sampling rate?

Looking forward to hearing whether this fixes it!

**Comment by bywbilly** [comment]
Hey,
Thanks for your reply and fix. I tried to preprocess the data and remove the queue stuff, then the code run pretty well. And now I have no time to test your new code and new idea, I am sorry for that. But I think you fixed this buy anyway :)

**Comment by f90** [comment]
Good to hear! Seems like you modified/improved the code a lot, would you mind sharing it so I can integrate the improvements potentially, especiallyr egarding dataset input to prevent this type of error?
